import {getAppUser} from '../../lib/app-user';
import AccessNotice from '../access-notice';
import {requireChatGPTUser,chatGPTSignOutPath} from '../chatgpt-auth';
import {loadWorkspace} from '../../db';
export const dynamic='force-dynamic';
export default async function Account(){
 await requireChatGPTUser('/account');let user;try{user=await getAppUser();}catch{return <AccessNotice title="Temporarily unavailable" message="Please refresh to load your account."/>;}if(!user||user.status!=='active')return <AccessNotice title="Account suspended" message="Contact your site administrator to restore access."/>;let record:null|Awaited<ReturnType<typeof loadWorkspace>>=null;let unavailable=false;try{record=await loadWorkspace(user.userId);}catch{unavailable=true;}const state=record?JSON.parse(record.state_json):null;
 return <main className="account-shell"><header className="account-header"><a className="auth-brand" href="/"><span>N</span> nxance.</a><a className="back-link" href="/workspace">← Back to workspace</a></header><div className="eyebrow">YOUR ACCOUNT</div><h1>A workspace that stays with you.</h1><p>Manage your session and check your saved work.</p><div className="account-grid"><section className="account-card"><h2>Profile</h2><dl><dt>Name</dt><dd>{user.fullName??'Not provided by your account'}</dd><dt>Email</dt><dd>{user.email}</dd><dt>Account role</dt><dd>{user.isOwner?'Owner':user.role==='admin'?'Administrator':'Member'}</dd><dt>Sign-in method</dt><dd>ChatGPT account</dd></dl><p className="muted-note">Your profile details come from ChatGPT. Nxance does not create or store a separate password.</p></section><section className="account-card"><h2>Saved workspace</h2>{unavailable?<p className="save-error">Your saved workspace is temporarily unavailable. Please refresh to try again.</p>:record?<dl><dt>Saved holdings</dt><dd>{state.holdings.length}{state.sampleMode?' · sample portfolio':''}</dd><dt>Goal target</dt><dd>{new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(state.goal.target)}</dd><dt>Last saved</dt><dd>{new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(record.updated_at))} UTC</dd></dl>:<p>No saved workspace yet. Add your holdings or explore a sample, set your goal assumptions, then choose Save workspace.</p>}<a className="primary-link" href="/workspace">{record?'Continue my workspace':'Open workspace'} <span aria-hidden="true">↗</span></a></section></div>{user.role==='admin'&&<p><a className="back-link" href="/admin">Open admin panel →</a></p>}<div className="account-foot"><p>Your saved holdings and goal assumptions are linked to your account. Administrators can review and manage this data. Signing out keeps saved work intact.</p><a href={chatGPTSignOutPath('/')} target="_top">Sign out of Nxance</a></div></main>;
}
