import {getAppUser} from '../../../lib/app-user';
import {getDb,loadWorkspace} from '../../../db';
import {workspaceInput} from '../../../lib/workspace-validation';
export const dynamic='force-dynamic';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
export async function GET(){let user;try{user=await getAppUser();}catch{return json({error:'Account services are temporarily unavailable. Please try again.'},503);}if(!user)return json({error:'Please sign in again.'},401);if(user.status!=='active')return json({error:'Your account is suspended. Contact the site administrator.'},403);try{const record=await loadWorkspace(user.userId);return json({user:{name:user.fullName,email:user.email,isAdmin:user.role==='admin'},state:record?JSON.parse(record.state_json):null,revision:record?.revision??0,updatedAt:record?.updated_at??null});}catch{console.error('Workspace load failed');return json({error:'Your saved workspace is temporarily unavailable. Please reload to try again.'},503);}}
export async function PUT(request:Request){
 let user;try{user=await getAppUser();}catch{return json({error:'Account services are temporarily unavailable. Please try again.'},503);}if(!user)return json({error:'Please sign in again. Your unsaved entries remain on this page.'},401);
 if(user.status!=='active')return json({error:'Your account is suspended. Contact the site administrator.'},403);
 const origin=request.headers.get('origin'),fetchSite=request.headers.get('sec-fetch-site');if((fetchSite&&fetchSite!=='same-origin')||!origin||![new URL(request.url).origin,'https://nxance-basics-bhaskar.bhaskar2708.chatgpt.site'].includes(origin)||request.headers.get('x-nxance-request')!=='save'||!request.headers.get('content-type')?.startsWith('application/json'))return json({error:'This save request could not be verified.'},403);
 let input;try{const body=await request.text();if(body.length>50000)return json({error:'This workspace is too large.'},413);input=workspaceInput.parse(JSON.parse(body));}catch{return json({error:'Check your holdings and goal values before saving.'},400);}
 try{const db=getDb(),now=new Date().toISOString(),state=JSON.stringify(input.state);const saved=input.revision===0?await db.prepare('INSERT INTO workspaces (user_id,state_json,revision,updated_at) VALUES (?,?,1,?) ON CONFLICT(user_id) DO NOTHING RETURNING revision,updated_at').bind(user.userId,state,now).first():await db.prepare('UPDATE workspaces SET state_json=?, revision=revision+1, updated_at=? WHERE user_id=? AND revision=? RETURNING revision,updated_at').bind(state,now,user.userId,input.revision).first();if(!saved)return json({error:'Your workspace was saved in another tab. Your edits remain here. Reload to review the latest saved version before saving again.'},409);return json({revision:(saved as {revision:number}).revision,updatedAt:now});}catch{console.error('Workspace save failed');return json({error:'We could not save your workspace. Your edits are still here; please try again.'},503);}
}
